### ISSUE TITLE
OC-sdk sends different sender id's onNewMessage Event and onTyping Event.

### ISSUE THREAD

**Issue by amitNinjax2730** [microsoft/omnichannel-chat-sdk#165]

**Comment by xTEddie** [comment]
It is by design that there's multiple sender ids.

In a chat, it usually contains three different users:
- system
- customer
- agent

A message should always be coming from one of the three participants and a typing event should always be coming from the agent. 

You can find the list of participants in the network traces with the `/chat/threads/[threadId]/participants` API.

A system user's responsibility is to send `system` messages in the chat. A system message will always contain the message tag `system`.
