### ISSUE TITLE
Agent not sending any system message when agent changes the activity state

### ISSUE THREAD

**Issue by amitNinjax2730** [microsoft/omnichannel-chat-sdk#175]
1) If i started the chat and agent is offline, it does not send any system message

2) Once chat is started and agent in between changes its state to offline or busy, it does not send any system message.

**Comment by amitNinjax2730** [comment]
After the update 
System message "An agent will be with you in a moment." is also not coming. It is shown when i reload the chat

**Comment by xTEddie** [comment]
Omnichannel is taking an external messaging client as dependency. The messaging client is using WebSocket and the connection may drop intermittently, so a polling mechanism is added to recover the messages. The polling interval is currently set at 30 seconds due to some technical constraints.

If WebSocket connection could not be established at t0 while the system message is suppose to come at t0, the message would be missed, then polling would retrieve the message at t30 instead.

On reloading the chat, the messages would be retrieve through a HTTP call which explains why it was retrieved.

**Comment by aanand07** [comment]
Hi @xTEddie ,

If the initial message "An agent will be with you in a moment." can't be subscribed in the `onNewMessage` api then what's the point of sending it.
IMO this is a bad user experience if this message isn't shown initially but then on reload it appears.
