### ISSUE TITLE
Uncaught runtime errors : ChatConfigRetrievalFailure

### ISSUE THREAD

**Issue by saikiran-48** [microsoft/omnichannel-chat-sdk#270]
![image](https://github.com/microsoft/omnichannel-chat-sdk/assets/54521490/4f88a68a-1a56-45b5-ba58-ad387d4ce9a5)

**Comment by xTEddie** [comment]
`ChatConfigRetrievalFailure` happens when we're unable to retrieve the configuration of the chat widget. 

It could be caused by the configuration not being fully synced in the DB upon creation. It could take some time for the new configuration to be synced. 

It could also happen if the configuration cannot be found in the DB due to the configuration that has already been deleted and does not exist anymore. 

I'd suggest to retry a few moment later or verify the chat widget still exists in the admin portal.
