### ISSUE TITLE
ChatSDK with BotFramework-WebChat doesnt Event type Activities

### ISSUE THREAD

**Issue by mehmetyuksel-to** [microsoft/omnichannel-chat-sdk#358]
We connect to omnichannel over Copilot using BotFramework-WebChat.

We were able to process Event Activities coming from Copilot before, but with this migration, useActivities hook only returns Message types now.

Is this a known issue? Any plans for mitigation?

**Comment by xTEddie** [comment]
Sending `event` activity is a `DirectLine` messaging protocol concept. Copilot Studio is using this protocol by default. However, `Omnichannel for Customer Service` is not using `DirectLine` messaging protocol. So, it is currently not supported.

**Comment by arnavsimer** [comment]
@xTEddie how can i achieve the same in `Omnichannel for Customer Service` then. because this is something which is very critical for me.
I first created a agent in copilot studio and created a FE using Botframework WebChat. But once i added live agent handoff i am forced to use Omnichannel's FE SDK. In my earlier implementation i use to call topics in copilot studio where trigger is `event `.
But now i find it difficult how to achieve something same in OC SDK. Can you tell me any workarounds. Because this is a serious issue for our client
